name: Python CI

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  python-ci:
    uses: BananaLoaf/ci-cd/.github/workflows/python-ci.yml@master
    with:
      skip-typecheck: true
      skip-test: true
      ruff-path: custom_components/365gps tests/

  python-build:
    uses: BananaLoaf/ci-cd/.github/workflows/python-build.yml@master
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.base_ref == 'master' || github.base_ref == 'main'
    name: python-build
    needs: python-ci
